site_name: TACC HPC Documentation
site_description: TACC Technical Documentation
site_author: Susan Lindsey
site_url: https://docs.tacc.utexas.edu
repo_url: https://github.com/TACC/TACC-Docs
edit_uri: edit/main/docs/

theme:
  name: tacc_readthedocs
  # "ReadTheDocs" Theme Features
  logo: /imgs/tacc-logo-with-words.svg
  analytics:
    gtag: G-TRRRQZ0EHX
  # "TACC" Theme Features
  portal_url: https://tacc.utexas.edu
  portal_name: tacc.utexas.edu
  hljs_aliases:
    - name: cmd-line
      lang: bash
    - name: job-script
      lang: bash
    - name: syntax
      lang: plaintext

extra_css:
  - css/extra.css

markdown_extensions:
  - extra
  - admonition
  - toc:
      permalink: "" # i.e. `true` but without "¶"
      permalink_class: headerlink fa fa-link
      permalink_title: Link to Heading
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.html
  - pymdownx.blocks.tab
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.saneheaders

nav:
  - TACC Essentials:
    - Documentation Overview: index.md
    - Getting Started: https://www.tacc.utexas.edu/use-tacc/getting-started/
    - Managing Your TACC Account: basics/accounts.md
    - Multi-Factor Authentication: basics/mfa.md
    - TACC Good Conduct Guide: basics/conduct.md
    - Data Transfer Guide: basics/datatransfer.md
    - Software at TACC: basics/software.md
    - Help: basics/help.md
  - HPC User Guides:
    - Chameleon: https://chameleoncloud.readthedocs.io/en/latest
    - Corral: hpc/corral.md
    - Frontera: hpc/frontera.md
    - Lonestar6: hpc/lonestar6.md
    - Jetstream2: https://docs.jetstream-cloud.org
    - Ranch: hpc/ranch.md
    - Stampede3: hpc/stampede3.md
    - Stallion: hpc/stallion.md
    - Vista: hpc/vista.md
  - Software Packages:
    - AlphaFold2 : software/alphafold.md
    - AlphaFold3 : software/alphafold3.md
    - ANSYS: software/ansys.md
    - CD Tools: software/cdtools.md
    - Gaussian: software/gaussian.md
    - GROMACS: software/gromacs.md
    - idev: software/idev.md
    - LAMMPS: software/lammps.md
    - Lmod: https://lmod.readthedocs.io/en/latest
    - MATLAB: software/matlab.md
    - NAMD: software/namd.md
    - OpenFOAM: software/openfoam.md
    - ParaView: software/paraview.md
    - PyLauncher: software/pylauncher.md
    - Quantum Espresso: software/quantumespresso.md 
    - REMORA: software/remora.md
    - TAU: software/tau.md
    - VASP: software/vasp.md
    - VisIt: software/visit.md
  - TACC Tutorials:
    - Access Control Lists: tutorials/acls.md
    - Bash Quick Start Guide: tutorials/bashstartup.md
    - BLAS/LAPACK: tutorials/blas-lapack.md
    - Containers at TACC: https://containers-at-tacc.readthedocs.io/en/latest/index.html
    - DDT Debugger: tutorials/ddt.md
    - Managing Group Permissions: tutorials/permissions.md
    - Managing I/O: tutorials/managingio.md
    - MAP: tutorials/map.md
    - Remote Desktop Access: tutorials/remotedesktopaccess.md
    - Sharing Project Files: tutorials/sharingprojectfiles.md
    - TACC Analysis Portal (TAP): tutorials/TAP.md



plugins:
  - search
  - exclude-search:
      exclude:
        - aliases.md
        - archives/*
        - include/*
        - code-examples/*
      exclude_unreferenced: true
  - macros # allows {% include ... %} (and macros)

# NOTE: warnings if file included by {% include '…' %} has relative paths
