site_name: Costa Rica AI Workshop 2025
site_description: Costa Rica AI Workshop 2025
site_author: Susan Lindsey
#site_url: https://docs.tacc.utexas.edu
#repo_url: https://github.com/TACC/TACC-Docs

theme:
  name: tacc_readthedocs
  # "ReadTheDocs" Theme Features
  logo: /imgs/tacc-logo-with-words.svg
  # "TACC" Theme Features
  #portal_url: https://tacc.utexas.edu
  #portal_name: tacc.utexas.edu
  #hljs_aliases:
  #  - name: cmd-line
  #    lang: bash
  #  - name: job-script
  #    lang: bash
  #  - name: syntax
  #    lang: plaintext

extra_css:
  - css/extra.css

markdown_extensions:
  - extra
  - admonition
  - toc:
      permalink: "" # i.e. `true` but without "¶"
      permalink_class: headerlink fa fa-link
      permalink_title: Link to Heading
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.html
  - pymdownx.blocks.tab
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.saneheaders

nav:
	tessa.md


plugins:
  - search
#  - exclude-search:
#      exclude:
#        - aliases.md
#        - archives/*
#        - include/*
#        - code-examples/*
#      exclude_unreferenced: true
#  - macros # allows {% include ... %} (and macros)

# NOTE: warnings if file included by {% include '…' %} has relative paths
