[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SDL Costa Rica""
authors = [{name = "Susan Lindsey", email = "slindsey@tacc.utexas.edu"}]
dynamic = ["version", "description"]
